// Central icon map so content (lib/data.js) can stay plain data.
import {
  FiScissors,
  FiInstagram,
  FiYoutube,
  FiLayers,
  FiSliders,
  FiTrendingUp,
  FiDroplet,
  FiFilm,
  FiZap,
  FiSmartphone,
  FiVideo,
  FiAward,
  FiUsers,
  FiClock,
  FiLinkedin,
  FiTwitter,
  FiMail,
  FiPhone,
  FiMapPin,
} from "react-icons/fi";
import { FaWhatsapp, FaBehance } from "react-icons/fa6";

export const icons = {
  scissors: FiScissors,
  instagram: FiInstagram,
  youtube: FiYoutube,
  layers: FiLayers,
  sliders: FiSliders,
  trending: FiTrendingUp,
  droplet: FiDroplet,
  film: FiFilm,
  zap: FiZap,
  smartphone: FiSmartphone,
  video: FiVideo,
  award: FiAward,
  users: FiUsers,
  clock: FiClock,
  linkedin: FiLinkedin,
  twitter: FiTwitter,
  behance: FaBehance,
  whatsapp: FaWhatsapp,
  mail: FiMail,
  phone: FiPhone,
  mapPin: FiMapPin,
};
